version: "3"

services:
  server:
    container_name: server
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres
    environment:
      PORT: 3000
      PG_PORT: 5432
      PG_USER: ${POSTGRES_USER}
      PG_PASSWORD: ${POSTGRES_PASSWORD}
      PG_DB_NAME: ${POSTGRES_DB}
      PG_HOST: ${POSTGRES_HOST}

  postgres:
    container_name: postgres
    image: postgres:14-alpine
    restart: on-failure
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db:/var/lib/postgresql/data
      - ../data:/var/lib/postgresql/csvs
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  client:
    container_name: client
    restart: always
    build:
      context: ./client
      target: builder
    command: npm start
    ports:
      - 4200:4200
    depends_on:
      - server
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  db:
    driver: local
